### ISSUE TITLE
file   zk-persistent existing problem

### ISSUE THREAD

**Issue by post707** [engapa/zookeeper-docker#1]
There is a problem with your file format

volumeClaimTemplates and securityContext  field  are wrong

**Comment by engapa** [comment]
[*]-persistent.yaml files were tested within Openshift (3.6, 3.7) and both of them were deployed successfully.

For kubernetes, you're right:

```bash
$ kubectl create -f zk-persistent.yaml
error: error validating "zk-persistent.yaml": error validating data: [found invalid field volumeClaimTemplates for v1.PodTemplateSpec, found invalid field fsGroup for v1.SecurityContext]; if you choose to ignore these errors, turn validation off with --validate=false
```
I've just pushed a commit to solve this error, thanks a lot for report that ;-)
